name: flutter_tutorial
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-84.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  android_id: ^0.3.3
  permission_handler: ^10.2.0

  path: ^1.8.3
  path_provider: ^2.0.15
  camera: ^0.10.5+2
  gallery_saver: ^2.3.2

  image_picker: ^0.8.7+4
  easy_image_viewer: ^1.2.0
  zoom_pinch_overlay: ^1.4.1+3
  audioplayers: ^5.0.0
  stamp_image: ^0.0.2

  dio: ^5.1.2
  http: ^0.13.6
  nfc_manager: ^3.2.0
  sqflite: ^2.2.8+4
  image: ^4.0.17

  dropdown_button2: ^2.1.2
  sn_progress_dialog: ^1.1.3
  flutter_smart_dialog: ^4.9.0+6

  flutter_cupertino_datetime_picker: ^3.0.0

  intl: ^0.18.1
  yaml: ^3.1.2
#  photo_view: ^0.14.0
  dropdownfield2: ^1.0.7
#  image: any
  #  flutter_launcher_icons: ^0.13.1
  #  thumbnailer: ^2.2.0
#  image_watermark: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# command-line: flutter pub run flutter_launcher_icons -f music-144
flutter_launcher_icons:
  image_path_android: "assets/music-144.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/loading/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

